/* ROBOT PROGRAMMER MANAGER V6 — ONLINE */
const KEY='robotProgrammerManagerV6Cache';
const CONFIG=window.SUPABASE_CONFIG||{};
let sb=null;
let session=null;
let cloudReady=false;
let realtimeChannel=null;
let db=JSON.parse(localStorage.getItem(KEY)||'null');
if(!db){
  const old=JSON.parse(localStorage.getItem('robotProgrammerManagerV1')||'null');
  db=old&&Array.isArray(old.robots)?old:{robots:[],selectedRobot:null,settings:{},overhang:{old:[],new:[]}};
}
const $=s=>document.querySelector(s);
const app=$('#app');
const pageTitles={dashboard:'Dashboard',robots:'Robots',calibration:'Calibration',io:'I/O Configuration',ethernet:'Ethernet Configuration',overhang:'Overhang Generator',panel:'Panel Diagram',details:'Other Details',backup:'Backup / Restore'};
const ioTypes=[['digitalIn','DIGITAL INPUT'],['digitalOut','DIGITAL OUTPUT'],['universalIn','UNIVERSAL INPUT'],['universalOut','UNIVERSAL OUTPUT']];

function isConfigured(){return CONFIG.url&&CONFIG.publishableKey&&/^https:\/\/[^.]+\.supabase\.co/.test(CONFIG.url)&&!CONFIG.publishableKey.includes('YOUR_')}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function uid(){return crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+'-'+Math.random().toString(36).slice(2)}
function toast(msg,kind='normal'){let x=document.createElement('div');x.textContent=msg;x.className='v6-toast '+kind;document.body.appendChild(x);setTimeout(()=>x.remove(),2400)}
function localSave(){localStorage.setItem(KEY,JSON.stringify(db))}
function robot(){return db.robots.find(r=>r.id===db.selectedRobot)||db.robots[0]}
function ensureIO(r){r.io ||= {}; for(const [key] of ioTypes){r.io[key]=Array.isArray(r.io[key])?r.io[key]:[]; while(r.io[key].length<10)r.io[key].push({range:'',rack:'',slot:'',start:''}); r.io[key]=r.io[key].slice(0,10).map(x=>({range:x?.range??x?.address??'',rack:x?.rack??x?.name??'',slot:x?.slot??x?.description??'',start:x?.start??x?.device??''}))} r.io.notes ||= ''}
function ensureData(r){
 r.calibration ||= {base:'',tcp:'',frame:'',payload:'',mastering:'',zero:'',notes:'',masterCounts:Array(9).fill('')};
 r.calibration.masterCounts=Array.isArray(r.calibration.masterCounts)?r.calibration.masterCounts:Array(9).fill(''); while(r.calibration.masterCounts.length<9)r.calibration.masterCounts.push('');
 ensureIO(r);
 r.ethernet ||= {robotIP:'',controller:'',subnet:'',gateway:'',dns:'',mac:'',ports:[],notes:''};
 r.overhang ||= {old:[],new:[]}; r.panel ||= {items:[]};
 r.details ||= {manufacturer:'',model:'',controller:'',software:'',welding:'',cell:'',programPath:'',backupPath:'',notes:''};
 r.manufacturer ??= r.details.manufacturer||''; r.model ??= r.details.model||'';
}
function normalizeRobot(r){ensureData(r);r.manufacturer=r.manufacturer||r.details.manufacturer||'';r.model=r.model||r.details.model||'';return r}
function cacheAndRender(msg='Saved locally'){localSave();render();toast(msg)}

async function cloudSaveRobot(r,section='general',action='update'){
 if(!cloudReady||!session)return false;
 normalizeRobot(r);
 const row={id:r.id,name:r.name||'Unnamed Robot',manufacturer:r.manufacturer||'',model:r.model||'',data:r,updated_by:session.user.id};
 const {error}=await sb.from('robots').upsert(row,{onConflict:'id'});
 if(error)throw error;
 const {error:historyError}=await sb.from('change_history').insert({robot_id:r.id,user_id:session.user.id,section,action,details:{robot_name:r.name||'',section}});
 if(historyError)console.warn('History insert failed:',historyError.message);
 return true;
}
async function cloudDeleteRobot(id,name){
 if(!cloudReady||!session)return false;
 const {error}=await sb.from('robots').delete().eq('id',id);if(error)throw error;
 const {error:he}=await sb.from('change_history').insert({robot_id:null,user_id:session.user.id,section:'robots',action:'delete',details:{robot_id:id,robot_name:name||''}});if(he)console.warn(he.message);
 return true;
}
function rowToRobot(row){let r=row.data&&typeof row.data==='object'?row.data:{};r.id=row.id;r.name=row.name||r.name||'Unnamed Robot';r.manufacturer=row.manufacturer||r.manufacturer||'';r.model=row.model||r.model||'';return normalizeRobot(r)}
async function loadCloud(){
 if(!cloudReady||!session)return;
 const {data,error}=await sb.from('robots').select('*').order('name');
 if(error){toast('Cloud load failed: '+error.message,'error');return}
 db.robots=(data||[]).map(rowToRobot); if(db.selectedRobot&&!db.robots.some(r=>r.id===db.selectedRobot))db.selectedRobot=db.robots[0]?.id||null; if(!db.selectedRobot)db.selectedRobot=db.robots[0]?.id||null; localSave();render();
}
function subscribeRealtime(){
 if(!cloudReady||!session)return;
 if(realtimeChannel)sb.removeChannel(realtimeChannel);
 realtimeChannel=sb.channel('robot-programmer-manager-robots')
 .on('postgres_changes',{event:'*',schema:'public',table:'robots'},payload=>{
   if(payload.eventType==='DELETE'){db.robots=db.robots.filter(r=>r.id!==payload.old.id);if(db.selectedRobot===payload.old.id)db.selectedRobot=db.robots[0]?.id||null}
   else {const incoming=rowToRobot(payload.new);const i=db.robots.findIndex(r=>r.id===incoming.id);if(i>=0)db.robots[i]=incoming;else db.robots.push(incoming);db.robots.sort((a,b)=>(a.name||'').localeCompare(b.name||''))}
   localSave();render();toast('Robot data updated by another programmer','online');
 }).subscribe(status=>{cloudReady=status==='SUBSCRIBED'||cloudReady;updateOnlineBadge(status==='SUBSCRIBED')});
}
function updateOnlineBadge(online){const b=$('#onlineBadge');if(b){b.textContent=online?'ONLINE':'CLOUD CONNECTING';b.className='badge '+(online?'online':'')+(online?'':' cloud-badge')}}

async function initCloud(){
 if(!isConfigured()){showSetup();return}
 sb=window.supabase.createClient(CONFIG.url,CONFIG.publishableKey);
 const {data,error}=await sb.auth.getSession(); if(error){showAuth(error.message);return}
 session=data.session;
 sb.auth.onAuthStateChange((_event,s)=>{session=s;if(s){setTimeout(async()=>{showApp();await loadCloud();subscribeRealtime()},0)}else{cloudReady=false;if(realtimeChannel)sb.removeChannel(realtimeChannel);showAuth()}});
 if(session){showApp();await loadCloud();subscribeRealtime()}else showAuth();
}
function showSetup(){document.body.classList.add('auth-mode');$('#auth').classList.remove('hidden');$('#auth').innerHTML=`<div class="auth-card"><div class="brand auth-brand"><div class="brand-mark">RP</div><div><b>ROBOT PROGRAMMER</b><small>MANAGER V6</small></div></div><h2>Supabase setup required</h2><p class="muted">The V6 Online version needs your Supabase project URL and publishable key.</p><div class="notice"><b>Open <code>supabase-config.js</code></b><br>Replace the two placeholder values, then upload the file to GitHub Pages.</div><p class="muted small">Do not put a service_role or secret key in the website.</p><button class="btn primary full-btn" onclick="location.reload()">CHECK CONFIG AGAIN</button><a class="setup-link" href="SETUP_SUPABASE.md" target="_blank">Open setup guide</a></div>`}
function showAuth(errorMsg=''){document.body.classList.add('auth-mode');$('#auth').classList.remove('hidden');$('#auth').innerHTML=`<div class="auth-card"><div class="brand auth-brand"><div class="brand-mark">RP</div><div><b>ROBOT PROGRAMMER</b><small>MANAGER V6 — ONLINE</small></div></div><h2>Programmer Login</h2><p class="muted">Sign in to access the shared robot database.</p>${errorMsg?`<div class="notice error-box">${esc(errorMsg)}</div>`:''}<div class="form-group"><label>Email</label><input id="authEmail" type="email" autocomplete="email" placeholder="programmer@company.com"></div><div class="form-group"><label>Password</label><input id="authPassword" type="password" autocomplete="current-password" placeholder="Password"></div><div class="actions auth-actions"><button class="btn primary" onclick="login()">LOGIN</button><button class="btn secondary" onclick="signup()">CREATE ACCOUNT</button></div><button class="text-btn" onclick="resetPassword()">Forgot password?</button><div class="cloud-note">Shared database • Supabase Auth • Realtime sync</div></div>`}
async function login(){const email=$('#authEmail').value.trim(),password=$('#authPassword').value;if(!email||!password)return toast('Enter email and password','error');const {error}=await sb.auth.signInWithPassword({email,password});if(error)toast(error.message,'error')}
async function signup(){const email=$('#authEmail').value.trim(),password=$('#authPassword').value;if(!email||!password)return toast('Enter email and password','error');if(password.length<6)return toast('Password must be at least 6 characters','error');const {data,error}=await sb.auth.signUp({email,password});if(error)return toast(error.message,'error');if(!data.session)toast('Account created. Check your email for confirmation.','online');else toast('Account created','online')}
async function resetPassword(){const email=prompt('Enter your company email address:');if(!email)return;const {error}=await sb.auth.resetPasswordForEmail(email.trim(),{redirectTo:location.href});toast(error?error.message:'Password reset email sent','online')}
async function logout(){await sb.auth.signOut()}
window.login=login;window.signup=signup;window.resetPassword=resetPassword;window.logout=logout;

function showApp(){$('#auth').classList.add('hidden');document.body.classList.remove('auth-mode');$('#appShell').classList.remove('hidden');}
function save(){localSave();render();toast(cloudReady?'Saved cache — use module Save to sync online':'Saved locally')}
async function saveCurrentRobot(section='general',action='update',message='Saved online'){
 const r=robot();if(!r)return;
 normalizeRobot(r);localSave();
 if(cloudReady){try{await cloudSaveRobot(r,section,action);toast(message,'online')}catch(e){toast('Saved locally, cloud error: '+e.message,'error');return false}}
 else toast('Saved locally');
 render();return true;
}
function changeGlobalRobot(id){if(!id)return;db.selectedRobot=id;localSave();render()}
window.changeGlobalRobot=changeGlobalRobot;
function nav(page){document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.page===page));location.hash=page;render()}
function bindStatic(){document.querySelectorAll('.nav-item').forEach(x=>x.onclick=()=>{nav(x.dataset.page);$('#sidebar').classList.remove('open')});$('#menuBtn').onclick=()=>$('#sidebar').classList.toggle('open');$('#quickSave').onclick=()=>saveCurrentRobot('quick-save','update','Saved online');$('#addRobotTop').onclick=()=>openRobotModal();$('#modalClose').onclick=closeModal;$('#modal').onclick=e=>{if(e.target.id==='modal')closeModal()}}
function render(){
 const page=location.hash.slice(1)||'dashboard';$('#pageTitle').textContent=pageTitles[page]||'Dashboard';
 $('#onlineBadge').textContent=cloudReady?'ONLINE':'LOCAL';$('#onlineBadge').className='badge '+(cloudReady?'online':'');
 $('#currentRobotLabel').innerHTML=`<label class="top-robot-label">ROBOT <select onchange="changeGlobalRobot(this.value)">${db.robots.length?db.robots.map(r=>`<option value="${esc(r.id)}" ${r.id===db.selectedRobot?'selected':''}>${esc(r.name)}${r.model?' • '+esc(r.model):''}</option>`).join(''):'<option>No Robot</option>'}</select></label>`;
 ({dashboard,robots,calibration,io,ethernet,overhang,panel,details,backup}[page]||dashboard)();
}
function needRobot(){app.innerHTML=`<div class="card"><div class="empty">Please add a robot first.<br><button class="btn primary" style="margin-top:12px" onclick="openRobotModal()">+ Add Robot</button></div></div>`}
function dashboard(){const r=robot();if(r)normalizeRobot(r);const ioCount=r?ioTypes.reduce((n,[k])=>n+r.io[k].filter(x=>Object.values(x).some(Boolean)).length,0):0;app.innerHTML=`<div class="grid"><div class="card"><span class="muted">TOTAL ROBOTS</span><div class="stat">${db.robots.length}</div></div><div class="card"><span class="muted">SELECTED ROBOT</span><div class="stat">${r?'1':'0'}</div></div><div class="card"><span class="muted">I/O ROWS USED</span><div class="stat">${ioCount}</div></div><div class="card"><span class="muted">SYNC</span><div class="stat">${cloudReady?'ON':'OFF'}</div></div></div><div class="grid-2" style="margin-top:16px"><div class="card"><div class="section-title"><h2>Robot Programmer Database</h2><button class="btn primary" onclick="openRobotModal()">+ Add Robot</button></div><p class="muted">Shared robot data for your programming team. Calibration, I/O, Ethernet, overhang, panel and cell information is synchronized through the online database.</p>${r?`<div class="kpi-list"><div class="kpi"><b>Robot</b><span>${esc(r.name)}</span></div><div class="kpi"><b>Model</b><span>${esc(r.model||'-')}</span></div><div class="kpi"><b>Controller</b><span>${esc(r.details.controller||'-')}</span></div><div class="kpi"><b>Robot IP</b><span class="mono">${esc(r.ethernet.robotIP||'-')}</span></div></div>`:`<div class="empty">Add your first robot.</div>`}</div><div class="card"><h2 style="margin-top:0">Online Status</h2><div class="online-panel"><span class="status-dot ${cloudReady?'on':''}"></span><div><b>${cloudReady?'CLOUD DATABASE CONNECTED':'LOCAL CACHE'}</b><p class="muted">${cloudReady?'Changes are shared with other signed-in programmers.':'Check Supabase setup/login to enable shared data.'}</p></div></div><div class="actions" style="margin-top:15px">${['calibration','io','ethernet','overhang','panel','details'].map(p=>`<button class="btn secondary" onclick="nav('${p}')">${pageTitles[p]}</button>`).join('')}</div></div></div>`}
function robots(){app.innerHTML=`<div class="card"><div class="section-title"><h2>Robot List</h2><button class="btn primary" onclick="openRobotModal()">+ Add Robot</button></div>${db.robots.length?`<div class="table-wrap"><table class="data-table"><tr><th>Name</th><th>Manufacturer</th><th>Model</th><th>Controller</th><th>IP</th><th>Status</th><th>Actions</th></tr>${db.robots.map(r=>{normalizeRobot(r);return`<tr><td><b>${esc(r.name)}</b></td><td>${esc(r.manufacturer||'-')}</td><td>${esc(r.model||'-')}</td><td>${esc(r.details.controller||'-')}</td><td class="mono">${esc(r.ethernet.robotIP||'-')}</td><td><span class="badge ${cloudReady?'online':'ok'}">${cloudReady?'ONLINE':'LOCAL'}</span></td><td class="actions"><button class="btn secondary" onclick="selectRobot('${r.id}')">Open</button><button class="btn secondary" onclick="openRobotModal('${r.id}')">Edit</button><button class="btn danger" onclick="deleteRobot('${r.id}')">Delete</button></td></tr>`}).join('')}</table></div>`:'<div class="empty">No robots added.</div>'}</div>`}
function selectRobot(id){db.selectedRobot=id;localSave();nav('dashboard')}
function openRobotModal(id=null){const r=id?db.robots.find(x=>x.id===id):null;$('#modalTitle').textContent=r?'Edit Robot':'Add Robot';$('#modalBody').innerHTML=`<div class="form-grid"><div class="form-group"><label>Robot Name *</label><input id="m_name" value="${esc(r?.name||'')}"></div><div class="form-group"><label>Manufacturer</label><input id="m_man" value="${esc(r?.manufacturer||'')}" placeholder="FANUC / KUKA / ABB / YASKAWA"></div><div class="form-group"><label>Robot Model</label><input id="m_model" value="${esc(r?.model||'')}"></div><div class="form-group"><label>Controller</label><input id="m_controller" value="${esc(r?.details?.controller||'')}"></div><div class="form-group full"><label>Notes</label><textarea id="m_notes">${esc(r?.details?.notes||'')}</textarea></div></div><div class="actions" style="margin-top:15px"><button class="btn primary" onclick="saveRobot('${id||''}')">Save Robot</button></div>`;$('#modal').classList.remove('hidden')}
async function saveRobot(id){let r=id?db.robots.find(x=>x.id===id):{id:uid(),name:'',manufacturer:'',model:'',calibration:{},io:{},ethernet:{ports:[]},overhang:{old:[],new:[]},panel:{items:[]},details:{}};r.name=$('#m_name').value.trim()||'Unnamed Robot';r.manufacturer=$('#m_man').value.trim();r.model=$('#m_model').value.trim();r.details.controller=$('#m_controller').value.trim();r.details.notes=$('#m_notes').value;normalizeRobot(r);if(!id)db.robots.push(r);db.selectedRobot=r.id;localSave();closeModal();if(cloudReady){try{await cloudSaveRobot(r,'robots',id?'update':'create');toast(id?'Robot updated online':'Robot created online','online')}catch(e){toast('Saved locally, cloud error: '+e.message,'error')}}else toast('Robot saved locally');nav('dashboard')}
async function deleteRobot(id){const r=db.robots.find(x=>x.id===id);if(!r||!confirm('Delete this robot and all its stored data from the shared database?'))return;db.robots=db.robots.filter(x=>x.id!==id);if(db.selectedRobot===id)db.selectedRobot=db.robots[0]?.id||null;localSave();if(cloudReady){try{await cloudDeleteRobot(id,r.name);toast('Robot deleted online','online')}catch(e){toast('Deleted locally, cloud error: '+e.message,'error')}}else toast('Robot deleted locally');nav('robots')}

function calibration(){const r=robot();if(!r)return needRobot();normalizeRobot(r);const c=r.calibration;app.innerHTML=`<div class="card calibration-card"><div class="section-title"><div><h2>Calibration</h2><p class="muted">Active robot: <b>${esc(r.name)}</b></p></div></div><div class="cal-tabs"><button class="cal-tab active" onclick="showCalibrationProcess(this)">1. FOLLOW CALIBRATION PROCESS</button><button class="cal-tab" onclick="showCalibrationValues(this)">2. CALIBRATION VALUES</button></div><div id="calibrationPanel"></div></div>`;showCalibrationProcess(document.querySelector('.cal-tab'))}
function showCalibrationProcess(btn){document.querySelectorAll('.cal-tab').forEach(x=>x.classList.remove('active'));btn.classList.add('active');$('#calibrationPanel').innerHTML=`<div class="cal-process-head"><div><h3>FOLLOW CALIBRATION PROCESS</h3><p class="muted">Calibration procedure document for the selected robot.</p></div><a class="btn primary" href="cal.pdf" target="_blank">OPEN PDF</a></div><div class="pdf-frame-wrap"><iframe class="cal-pdf" src="cal.pdf#view=FitH" title="Calibration Process PDF"></iframe></div>`}
function showCalibrationValues(btn){document.querySelectorAll('.cal-tab').forEach(x=>x.classList.remove('active'));btn.classList.add('active');const c=robot().calibration;$('#calibrationPanel').innerHTML=`<div class="section-title"><div><h3>CALIBRATION VALUES</h3><p class="muted">Enter the MASTER COUNT values for this robot. Values are stored in the shared database.</p></div><button class="btn primary" onclick="saveCalibrationValues()">SAVE VALUES</button></div><div class="cal-master-card"><div class="cal-master-title"><span class="mono">$DMR_GRP[1].$MASTER_COUN</span><span class="badge">MASTER COUNT</span></div><div class="table-wrap"><table class="data-table master-table"><tr><th>SR.NO</th><th>GROUP</th><th>MASTER COUNT</th></tr>${Array.from({length:9},(_,i)=>`<tr><td>${i+1}</td><td>[${i+1}]</td><td><input class="master-input" data-master-index="${i}" value="${esc(c.masterCounts[i]||'')}" type="number" step="1" placeholder="Enter value"></td></tr>`).join('')}</table></div></div><div class="form-grid" style="margin-top:16px">${[['base','BASE / J1 CALIBRATION'],['tcp','TCP / TOOL CALIBRATION'],['frame','USER FRAME / WORK OBJECT'],['payload','PAYLOAD / LOAD DATA'],['mastering','MASTERING / ZERO DATA'],['zero','ZERO POSITION / HOME DATA']].map(([k,l])=>`<div class="form-group"><label>${l}</label><textarea data-field="${k}" data-module="calibration">${esc(c[k]||'')}</textarea></div>`).join('')}<div class="form-group full"><label>CALIBRATION NOTES</label><textarea data-field="notes" data-module="calibration">${esc(c.notes||'')}</textarea></div></div>`}
async function saveCalibrationValues(){const r=robot();if(!r)return;normalizeRobot(r);r.calibration.masterCounts=Array.from({length:9},(_,i)=>document.querySelector(`[data-master-index="${i}"]`)?.value||'');document.querySelectorAll('[data-module="calibration"]').forEach(el=>r.calibration[el.dataset.field]=el.value);await saveCurrentRobot('calibration','update','Calibration saved online')}

function io(){const r=robot();if(!r)return needRobot();normalizeRobot(r);app.innerHTML=`<div class="card"><div class="section-title"><div><h2>I/O Configuration</h2><p class="muted">10 editable rows per configuration. Select the active robot from the top bar.</p></div><button class="btn primary" onclick="saveIO()">SAVE ALL I/O</button></div><div class="io-grid">${ioTypes.map(([type,title])=>`<div class="io-card"><div class="io-head"><h3>${title}</h3><button class="btn secondary small-btn" onclick="addIORow('${type}')">+ ADD</button></div><div class="table-wrap"><table class="data-table io-table"><tr><th>SR.NO</th><th>RANGE</th><th>RACK</th><th>SLOT</th><th>START</th></tr>${r.io[type].map((x,i)=>`<tr><td>${i+1}</td><td><input data-io-type="${type}" data-io-index="${i}" data-io-field="range" value="${esc(x.range)}"></td><td><input data-io-type="${type}" data-io-index="${i}" data-io-field="rack" value="${esc(x.rack)}"></td><td><input data-io-type="${type}" data-io-index="${i}" data-io-field="slot" value="${esc(x.slot)}"></td><td><input data-io-type="${type}" data-io-index="${i}" data-io-field="start" value="${esc(x.start)}"></td></tr>`).join('')}</table></div></div>`).join('')}</div><div class="form-group full" style="margin-top:16px"><label>I/O NOTES</label><textarea id="ioNotes">${esc(r.io.notes||'')}</textarea></div></div>`}
function addIORow(type){const r=robot();normalizeRobot(r);r.io[type].push({range:'',rack:'',slot:'',start:''});r.io[type]=r.io[type].slice(0,20);io()}
async function saveIO(){const r=robot();if(!r)return;normalizeRobot(r);document.querySelectorAll('[data-io-type]').forEach(el=>{r.io[el.dataset.ioType][Number(el.dataset.ioIndex)][el.dataset.ioField]=el.value});r.io.notes=$('#ioNotes').value;await saveCurrentRobot('io','update','I/O saved online')}

function ethernet(){const r=robot();if(!r)return needRobot();normalizeRobot(r);const e=r.ethernet;app.innerHTML=`<div class="card"><div class="section-title"><div><h2>Ethernet / Network Configuration</h2><p class="muted">Shared network configuration for ${esc(r.name)}.</p></div><button class="btn primary" onclick="saveModule('ethernet')">SAVE</button></div><div class="form-grid">${[['robotIP','Robot IP Address'],['controller','Controller / Network Name'],['subnet','Subnet Mask'],['gateway','Gateway'],['dns','DNS'],['mac','MAC Address']].map(([k,l])=>`<div class="form-group"><label>${l}</label><input data-field="${k}" data-module="ethernet" value="${esc(e[k]||'')}"></div>`).join('')}<div class="form-group full"><label>Ethernet Ports / Services (one per line)</label><textarea data-field="ports" data-module="ethernet">${esc((e.ports||[]).join('\n'))}</textarea></div><div class="form-group full"><label>Network Notes</label><textarea data-field="notes" data-module="ethernet">${esc(e.notes||'')}</textarea></div></div></div>`}
async function saveModule(module){const r=robot();if(!r)return;normalizeRobot(r);document.querySelectorAll(`[data-module="${module}"]`).forEach(el=>{let v=el.value;if(module==='ethernet'&&el.dataset.field==='ports')v=v.split('\n').filter(Boolean);r[module][el.dataset.field]=v});await saveCurrentRobot(module,'update',module.toUpperCase()+' saved online')}

function overhang(){const r=robot();if(!r)return needRobot();normalizeRobot(r);app.innerHTML=`<div class="card overhang-matrix-card"><div class="section-title"><div><h2>Overhang Matrix</h2><p class="muted">Old Fanuc and New Fanuc overhang generator</p></div></div><div class="sub-tab-container"><button id="sub-tab-old" class="sub-tab active" onclick="switchOverhangGen('old')">Old Fanuc</button><button id="sub-tab-new" class="sub-tab" onclick="switchOverhangGen('new')">New Fanuc</button></div><div id="overhang-old-content" class="sub-content active"><div class="card inner-card"><h2>Old Fanuc Overhang Configuration</h2><div class="form-grid"><div class="form-group"><label>X Coordinate</label><input type="number" id="old-x" value="0" step="0.001"></div><div class="form-group"><label>Y Coordinate</label><input type="number" id="old-y" value="0" step="0.001"></div><div class="form-group"><label>Z Coordinate</label><input type="number" id="old-z" value="0" step="0.001"></div><div class="form-group"><label>O (Overhang Base)</label><input type="number" id="old-o" value="0" step="0.001"></div></div><button class="btn primary full-btn" onclick="runOldOverhang()">SUBMIT (Calculate Old)</button></div><div class="card inner-card"><h2>Output Parameters</h2><div class="form-grid three-cols"><div class="form-group"><label>Output X</label><input type="text" id="old-ox" readonly></div><div class="form-group"><label>Output Y</label><input type="text" id="old-oy" readonly></div><div class="form-group"><label>Output Z</label><input type="text" id="old-oz" readonly></div></div></div></div><div id="overhang-new-content" class="sub-content"><div class="card inner-card"><h2>New Fanuc Offset Configuration</h2><div class="form-grid"><div class="form-group"><label>X Coordinate</label><input type="number" id="new-x" value="0" step="0.001"></div><div class="form-group"><label>Y Coordinate</label><input type="number" id="new-y" value="0" step="0.001"></div><div class="form-group"><label>Z Coordinate</label><input type="number" id="new-z" value="0" step="0.001"></div><div class="form-group"><label>O (Overhang Base)</label><input type="number" id="new-o" value="0" step="0.001"></div></div><button class="btn primary full-btn" onclick="runNewOverhang()">SUBMIT (Calculate New)</button></div><div class="card inner-card"><h2>Output Parameters</h2><div class="form-grid three-cols"><div class="form-group"><label>Output OX</label><input type="text" id="new-ox" readonly></div><div class="form-group"><label>Output OY</label><input type="text" id="new-oy" readonly></div><div class="form-group"><label>Output OZ</label><input type="text" id="new-oz" readonly></div></div></div></div></div>`}
function switchOverhangGen(mode){document.querySelectorAll('.sub-tab').forEach(el=>el.classList.remove('active'));document.querySelectorAll('.sub-content').forEach(el=>el.classList.remove('active'));const old=mode==='old';document.getElementById(old?'sub-tab-old':'sub-tab-new').classList.add('active');document.getElementById(old?'overhang-old-content':'overhang-new-content').classList.add('active')}
function runOldOverhang(){const x=parseFloat($('#old-x').value)||0,y=parseFloat($('#old-y').value)||0,z=parseFloat($('#old-z').value)||0,o=parseFloat($('#old-o').value)||0;const ox=x<0?-(0.707*o+Math.abs(x)):Math.abs(x)-0.707*o;const oz=z<0?-(0.707*o+Math.abs(z)):0.707*o+Math.abs(z);$('#old-ox').value=ox.toFixed(3);$('#old-oy').value=y;$('#old-oz').value=oz.toFixed(3)}
function runNewOverhang(){const x=parseFloat($('#new-x').value)||0,y=parseFloat($('#new-y').value)||0,z=parseFloat($('#new-z').value)||0,o=parseFloat($('#new-o').value)||0;const ox=x<0?-(0.574*o+Math.abs(x)):0.574*o+Math.abs(x);const oz=z<0?-(0.819*o+Math.abs(z)):0.819*o+Math.abs(z);$('#new-ox').value=ox.toFixed(3);$('#new-oy').value=y;$('#new-oz').value=oz.toFixed(3)}

function panel(){const r=robot();if(!r)return needRobot();normalizeRobot(r);app.innerHTML=`<div class="card panel-generator-card"><div class="section-title"><div><h2>Aluminium Panel Diagram</h2><p class="muted">Panel stiffener layout generator</p></div></div><div class="form-group"><label>Customer Selection</label><select id="customer" onchange="resetPanel()"><option value="STDREV_DECK">STDREV_DECK</option><option value="KALPATARU_DECK">KALPATARU_DECK</option><option value="RAGHAVAN">RAGHAVAN</option><option value="KALPATARU">KALPATARU</option><option value="STDREV">STDREV</option><option value="WT">WT</option><option value="WX">WX</option></select></div><div class="form-grid"><div class="form-group"><label>Width</label><input type="number" id="width" value="600"></div><div class="form-group"><label>Length</label><input type="number" id="length" value="2400"></div></div><button class="btn primary full-btn" onclick="generate()">Submit</button><div class="panel-note">NOTE : The gap is from center of stiffner to reference</div><div class="panel-scroll"><div id="panel" class="generated-panel"></div></div><div class="panel-summary" id="summary"></div><div class="gauge-box"><b>Gauge :</b><div id="gauge"></div></div></div>`;resetPanel()}
function generate(){let customer=$('#customer').value,length=parseInt($('#length').value);if(length>2500)return alert('Panel length cannot exceed 2500 mm.');if(length<=0||isNaN(length))return alert('Please enter a valid panel length.');const panelEl=$('#panel'),summary=$('#summary');panelEl.innerHTML='';summary.innerHTML='';let ratio=Math.min(0.3,700/length);panelEl.style.width=(length*ratio)+'px';let positions=[],gapPattern=[],typePattern=[];if(customer==='WT'||customer==='WX'){if(customer==='WT'){if(length>=250&&length<=365)positions.push(length/2);else if(length<=565)positions.push(250);else{let pos=250;positions.push(pos);while(true){pos+=200;if(pos>=length)break;positions.push(pos)}}}else{if(length>=250&&length<=599)positions.push(length/2);else if(length>=600&&length<=799){positions.push(200,length-200)}else if(length>=800){let pos=0;while(true){pos+=200;if(pos>=length)break;positions.push(pos)}}}if(positions.length&&length-positions.at(-1)<116)positions.pop();drawStiffeners(positions,['u'],ratio,panelEl,summary);return}if(customer==='STDREV_DECK'){gapPattern=[300];typePattern=['i']}if(customer==='KALPATARU_DECK'){gapPattern=[250,300,300,300,300,300,300,300];typePattern=Array(8).fill('i')}if(customer==='RAGHAVAN'){gapPattern=[225,250,275,275,275,300,275,300,225];typePattern=['u','ulip','u','ulip','u','ulip','u','u']}if(customer==='KALPATARU'){gapPattern=[225,225,275,275,300,300,300,300,200];typePattern=['u','ulip','u','ulip','u','ulip','u','u']}if(customer==='STDREV'){gapPattern=[225,225,275,275,300,300,300,350,150];typePattern=['u','ulip','u','ulip','u','ulip','u','u']}let center=0,gapIndex=0;while(gapPattern.length){let nextGap=gapPattern[gapIndex%gapPattern.length];center+=nextGap;if(center>=length)break;positions.push(center);gapIndex++}if(positions.length&&length-positions.at(-1)<116)positions.pop();drawStiffeners(positions,typePattern,ratio,panelEl,summary)}
function drawStiffeners(positions,typePattern,ratio,panelEl,summary,typeCountInput){let typeCount=typeCountInput||{u:0,ulip:0,i:0},gauges=[];positions.forEach((pos,i)=>{let type=typePattern[i%typePattern.length],stiff=document.createElement('div');stiff.classList.add('stiffener',type);stiff.style.left=(pos*ratio)+'px';panelEl.appendChild(stiff);typeCount[type]++;let gapValue=i===0?pos:pos-positions[i-1],gapLabel=document.createElement('div');gapLabel.className='label';gapLabel.innerText='Gap: '+gapValue+'MM';gapLabel.style.left=(pos*ratio-20)+'px';panelEl.appendChild(gapLabel);let stiffWidth=type==='u'?25:type==='ulip'?35:10;gauges.push(pos-stiffWidth);let typeLabel=document.createElement('div');typeLabel.className='panel-type-label';typeLabel.style.left=(pos*ratio-25)+'px';typeLabel.innerText=type==='u'?'Stiff-U':type==='ulip'?'Stiff-U Lip':'Stiff-I';panelEl.appendChild(typeLabel)});$('#gauge').innerText=gauges.join(' , ');summary.innerHTML=`Total Stiffeners: ${positions.length}<br>Stiff-U Count: ${typeCount.u}<br>Stiff-U Lip Count: ${typeCount.ulip}<br>Stiff-I Count: ${typeCount.i}`}
function resetPanel(){if($('#panel'))$('#panel').innerHTML='';if($('#summary'))$('#summary').innerHTML='';if($('#gauge'))$('#gauge').innerHTML=''}

function details(){const r=robot();if(!r)return needRobot();normalizeRobot(r);const d=r.details;app.innerHTML=`<div class="card"><div class="section-title"><h2>Other Robot / Cell Details</h2><button class="btn primary" onclick="saveModule('details')">SAVE</button></div><div class="form-grid">${[['manufacturer','Manufacturer'],['model','Robot Model'],['controller','Controller'],['software','Robot Software Version'],['welding','Welding Machine / Process'],['cell','Robot Cell / Line'],['programPath','Program Backup Path'],['backupPath','Full Backup Location']].map(([k,l])=>`<div class="form-group"><label>${l}</label><input data-field="${k}" data-module="details" value="${esc(d[k]||'')}"></div>`).join('')}<div class="form-group full"><label>Other Details / Notes</label><textarea data-field="notes" data-module="details">${esc(d.notes||'')}</textarea></div></div></div>`}

function backup(){app.innerHTML=`<div class="grid-2"><div class="card"><h2>Cloud Status</h2><p class="muted">${cloudReady?'Connected to the shared Supabase database.':'Not connected to the cloud.'}</p>${session?`<div class="kpi-list"><div class="kpi"><b>Programmer</b><span>${esc(session.user.email||'-')}</span></div><div class="kpi"><b>Robot Records</b><span>${db.robots.length}</span></div></div><button class="btn secondary" style="margin-top:12px" onclick="logout()">LOG OUT</button>`:''}</div><div class="card"><h2>Export Local Backup</h2><p class="muted">Download a JSON copy of the current browser cache.</p><button class="btn primary" onclick="exportDB()">DOWNLOAD BACKUP</button></div><div class="card"><h2>Import Local Backup</h2><p class="muted">Restore a JSON backup into this browser. It does not automatically overwrite the cloud.</p><input type="file" accept=".json,application/json" id="importFile"><button class="btn secondary" style="margin-top:10px" onclick="importDB()">RESTORE LOCAL</button></div><div class="card"><h2>Upload Local Data To Cloud</h2><p class="muted">Use this once to migrate correct V5/V6 local data into the shared database. Existing cloud robots with the same ID will be updated.</p><button class="btn success" onclick="uploadLocalToCloud()">UPLOAD TO CLOUD</button></div><div class="card full-span"><h2>V6 Online Data Flow</h2><div class="notice">Programmer A saves robot data → Supabase stores it → Realtime sends the change → Programmer B sees the updated data on the website.</div><p class="muted small" style="margin-top:12px">Each programmer needs their own Supabase login. The website itself is hosted by GitHub Pages; robot data is stored centrally in Supabase.</p></div></div>`}
function exportDB(){const blob=new Blob([JSON.stringify(db,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='ROBOT_PROGRAMMER_BACKUP.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function importDB(){const f=$('#importFile')?.files[0];if(!f)return alert('Select a backup file first.');const rd=new FileReader();rd.onload=()=>{try{const x=JSON.parse(rd.result);if(!x.robots)throw Error();db=x;db.robots.forEach(normalizeRobot);localSave();render();toast('Local backup restored. Cloud not changed.','online')}catch(e){alert('Invalid backup file.')}};rd.readAsText(f)}
async function uploadLocalToCloud(){if(!cloudReady)return alert('Log in to the cloud first.');if(!db.robots.length)return alert('No local robot data to upload.');if(!confirm(`Upload ${db.robots.length} local robot record(s) to the shared database?`))return;let ok=0;for(const r of db.robots){try{await cloudSaveRobot(r,'migration','import');ok++}catch(e){console.error(e)}}await loadCloud();toast(`${ok} robot record(s) uploaded to cloud`,'online')}

function closeModal(){$('#modal').classList.add('hidden')}
window.nav=nav;window.openRobotModal=openRobotModal;window.saveRobot=saveRobot;window.selectRobot=selectRobot;window.deleteRobot=deleteRobot;window.saveCalibrationValues=saveCalibrationValues;window.showCalibrationProcess=showCalibrationProcess;window.showCalibrationValues=showCalibrationValues;window.saveIO=saveIO;window.addIORow=addIORow;window.saveModule=saveModule;window.switchOverhangGen=switchOverhangGen;window.runOldOverhang=runOldOverhang;window.runNewOverhang=runNewOverhang;window.generate=generate;window.resetPanel=resetPanel;window.exportDB=exportDB;window.importDB=importDB;window.uploadLocalToCloud=uploadLocalToCloud;window.logout=logout;

bindStatic();
window.addEventListener('hashchange',render);
window.addEventListener('online',()=>{if(session)loadCloud()});
render();
initCloud();
