-- ============================================================
-- ROBOT PROGRAMMER MANAGER V6 - ONLINE
-- Supabase database schema
-- ============================================================

create table if not exists public.robots (
  id uuid primary key,
  name text not null,
  manufacturer text default '',
  model text default '',
  data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id) on delete set null
);

create table if not exists public.change_history (
  id bigint generated by default as identity primary key,
  robot_id uuid references public.robots(id) on delete cascade,
  user_id uuid references auth.users(id) on delete set null,
  section text not null default 'unknown',
  action text not null default 'update',
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists robots_updated_at_idx on public.robots(updated_at desc);
create index if not exists history_robot_id_idx on public.change_history(robot_id);
create index if not exists history_created_at_idx on public.change_history(created_at desc);

-- Automatically maintain updated_at.
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists robots_set_updated_at on public.robots;
create trigger robots_set_updated_at
before update on public.robots
for each row execute function public.set_updated_at();

-- RLS: only signed-in programmers can read/write robot data.
alter table public.robots enable row level security;
alter table public.change_history enable row level security;

drop policy if exists "Authenticated users can read robots" on public.robots;
drop policy if exists "Authenticated users can insert robots" on public.robots;
drop policy if exists "Authenticated users can update robots" on public.robots;
drop policy if exists "Authenticated users can delete robots" on public.robots;

create policy "Authenticated users can read robots"
on public.robots for select
to authenticated
using (true);

create policy "Authenticated users can insert robots"
on public.robots for insert
to authenticated
with check (true);

create policy "Authenticated users can update robots"
on public.robots for update
to authenticated
using (true)
with check (true);

create policy "Authenticated users can delete robots"
on public.robots for delete
to authenticated
using (true);

drop policy if exists "Authenticated users can read history" on public.change_history;
drop policy if exists "Authenticated users can insert history" on public.change_history;

create policy "Authenticated users can read history"
on public.change_history for select
to authenticated
using (true);

create policy "Authenticated users can insert history"
on public.change_history for insert
to authenticated
with check (true);

-- Enable Realtime for the robots table.
-- If this reports that the table is already a member, that is OK.
alter publication supabase_realtime add table public.robots;

-- Recommended Auth setting:
-- Authentication > Providers > Email: enable Email/Password.
-- For a private company app, keep email confirmation enabled if required by your policy.
